---
- name: Playbook1 run
  hosts: all
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/htmldav/test.git
      dest: /home/ubuntu/repos/
      clone: yes
      update: yes

  - name: "source code : local install"
    command: mvn --batch-mode --quiet install
    args:
      chdir: "/home/ubuntu/repos"

  - name: "create image"
    shell: | 
      docker build -t diplom . 
      docker tag diplom aldav99/diplom
      echo "Gfdkjdcrfz25" | docker login --username aldav99 --password-stdin docker.io 
      docker push aldav99/diplom
    args:
      chdir: "/home/ubuntu/repos"