---
- name: Test playbook run
  hosts: all
  become: yes

  tasks:
  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Clone a github repository
    git:
      repo: https://github.com/htmldav/test.git
      dest: ~/repos/
      clone: yes
      update: yes

  - name: "source code : local install"
    command: mvn --batch-mode --quiet install
    args:
      chdir: "~/repos"